version: '3.8'

services:
  mysql-spring:
    image: mysql:8.0
    container_name: mysql-spring
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: senagist_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springnet

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-senagist
    depends_on:
      - mysql-spring
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-spring:3306/senagist_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - springnet

volumes:
  mysql_data:

networks:
  springnet:
